library(tidyverse)

# Arizona
AZ_methods = read_csv("data/raw-data/WestDAAT/AZ/methods.csv")
AZ_organizations = read_csv("data/raw-data/WestDAAT/AZ/organizations.csv")
AZ_sites_missing = read_csv("data/raw-data/WestDAAT/AZ/sites_missing.csv")
AZ_sites = read_csv("data/raw-data/WestDAAT/AZ/sites.csv")
AZ_variables = read_csv("data/raw-data/WestDAAT/AZ/variables.csv")
AZ_allocations_missing = read_csv("data/raw-data/WestDAAT/AZ/waterallocations_missing.csv")
AZ_allocations = read_csv("data/raw-data/WestDAAT/AZ/waterallocations.csv")
AZ_sources_missing = read_csv("data/raw-data/WestDAAT/AZ/watersources_missing.csv")
AZ_sources = read_csv("data/raw-data/WestDAAT/AZ/watersources.csv")

# California CNRA
CA_CNRA_methods = read_csv("data/raw-data/WestDAAT/CA/CNRA/methods.csv")
CA_CNRA_organizations = read_csv("data/raw-data/WestDAAT/CA/CNRA/organizations.csv")
CA_CNRA_sites_missing = read_csv("data/raw-data/WestDAAT/CA/CNRA/sites_missing.csv")
CA_CNRA_sites = read_csv("data/raw-data/WestDAAT/CA/CNRA/sites.csv")
CA_CNRA_variables = read_csv("data/raw-data/WestDAAT/CA/CNRA/variables.csv")
CA_CNRA_allocations_missing = read_csv("data/raw-data/WestDAAT/CA/CNRA/waterallocations_missing.csv")
CA_CNRA_allocations = read_csv("data/raw-data/WestDAAT/CA/CNRA/waterallocations.csv")
CA_CNRA_sources_missing = read_csv("data/raw-data/WestDAAT/CA/CNRA/watersources_missing.csv")
CA_CNRA_sources = read_csv("data/raw-data/WestDAAT/CA/CNRA/watersources.csv")

# California CSWRCB
CA_CSWRCB_methods = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/methods.csv")
CA_CSWRCB_organizations = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/organizations.csv")
CA_CSWRCB_sites_missing = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/sites_missing.csv")
CA_CSWRCB_sites = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/sites.csv")
CA_CSWRCB_sites_amts_missing = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/sitespecificamounts_missing.csv")
CA_CSWRCB_sites_amts = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/sitespecificamounts.csv")
CA_CSWRCB_variables = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/variables.csv")
CA_CSWRCB_allocations_missing = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/waterallocations_missing.csv")
CA_CSWRCB_allocations = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/waterallocations.csv")
CA_CSWRCB_sources_missing = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/watersources_missing.csv")
CA_CSWRCB_sources = read_csv("data/raw-data/WestDAAT/CA/CSWRCB/watersources.csv")

# Colorado
CO_methods = read_csv("data/raw-data/WestDAAT/CO/methods.csv")
CO_organizations = read_csv("data/raw-data/WestDAAT/CO/organizations.csv")
CO_sites_missing = read_csv("data/raw-data/WestDAAT/CO/sites_missing.csv")
CO_sites = read_csv("data/raw-data/WestDAAT/CO/sites.csv")
CO_sites_amts_missing = read_csv("data/raw-data/WestDAAT/CO/sitespecificamounts_missing.csv")
CO_sites_amts = read_csv("data/raw-data/WestDAAT/CO/sitespecificamounts.csv")
CO_variables = read_csv("data/raw-data/WestDAAT/CO/variables.csv")
CO_allocations_missing = read_csv("data/raw-data/WestDAAT/CO/waterallocations_missing.csv")
CO_allocations = read_csv("data/raw-data/WestDAAT/CO/waterallocations.csv")
CO_sources_missing = read_csv("data/raw-data/WestDAAT/CO/watersources_missing.csv")
CO_sources = read_csv("data/raw-data/WestDAAT/CO/watersources.csv")

# Idaho
ID_methods = read_csv("data/raw-data/WestDAAT/ID/methods.csv")
ID_organizations = read_csv("data/raw-data/WestDAAT/ID/organizations.csv")
ID_sites_missing = read_csv("data/raw-data/WestDAAT/ID/sites_missing.csv")
ID_sites = read_csv("data/raw-data/WestDAAT/ID/sites.csv")
ID_variables = read_csv("data/raw-data/WestDAAT/ID/variables.csv")
ID_allocations_missing = read_csv("data/raw-data/WestDAAT/ID/waterallocations_missing.csv")
ID_allocations = read_csv("data/raw-data/WestDAAT/ID/waterallocations.csv")
ID_sources_missing = read_csv("data/raw-data/WestDAAT/ID/watersources_missing.csv")
ID_sources = read_csv("data/raw-data/WestDAAT/ID/watersources.csv")

# Kansas
KS_methods = read_csv("data/raw-data/WestDAAT/KS/methods.csv")
KS_organizations = read_csv("data/raw-data/WestDAAT/KS/organizations.csv")
KS_sites_missing = read_csv("data/raw-data/WestDAAT/KS/sites_missing.csv")
KS_sites = read_csv("data/raw-data/WestDAAT/KS/sites.csv")
KS_variables = read_csv("data/raw-data/WestDAAT/KS/variables.csv")
KS_allocations_missing = read_csv("data/raw-data/WestDAAT/KS/waterallocations_missing.csv")
KS_allocations = read_csv("data/raw-data/WestDAAT/KS/waterallocations.csv")
KS_sources_missing = read_csv("data/raw-data/WestDAAT/KS/watersources_missing.csv")
KS_sources = read_csv("data/raw-data/WestDAAT/KS/watersources.csv")

# Montana
MT_methods = read_csv("data/raw-data/WestDAAT/MT/methods.csv")
MT_organizations = read_csv("data/raw-data/WestDAAT/MT/organizations.csv")
MT_sites_missing = read_csv("data/raw-data/WestDAAT/MT/sites_missing.csv")
MT_sites = read_csv("data/raw-data/WestDAAT/MT/sites.csv")
MT_variables = read_csv("data/raw-data/WestDAAT/MT/variables.csv")
MT_allocations_missing = read_csv("data/raw-data/WestDAAT/MT/waterallocations_missing.csv")
MT_allocations = read_csv("data/raw-data/WestDAAT/MT/waterallocations.csv")
MT_sources_missing = read_csv("data/raw-data/WestDAAT/MT/watersources_missing.csv")
MT_sources = read_csv("data/raw-data/WestDAAT/MT/watersources.csv")

# North Dakota
ND_methods = read_csv("data/raw-data/WestDAAT/ND/methods.csv")
ND_organizations = read_csv("data/raw-data/WestDAAT/ND/organizations.csv")
ND_sites_missing = read_csv("data/raw-data/WestDAAT/ND/sites_missing.csv")
ND_sites = read_csv("data/raw-data/WestDAAT/ND/sites.csv")
ND_sites_amts_missing = read_csv("data/raw-data/WestDAAT/ND/sitespecificamounts_missing.csv")
ND_sites_amts = read_csv("data/raw-data/WestDAAT/ND/sitespecificamounts.csv")
ND_variables = read_csv("data/raw-data/WestDAAT/ND/variables.csv")
ND_allocations_missing = read_csv("data/raw-data/WestDAAT/ND/waterallocations_missing.csv")
ND_allocations = read_csv("data/raw-data/WestDAAT/ND/waterallocations.csv")
ND_sources_missing = read_csv("data/raw-data/WestDAAT/ND/watersources_missing.csv")
ND_sources = read_csv("data/raw-data/WestDAAT/ND/watersources.csv")

# Nebraska
NE_methods = read_csv("data/raw-data/WestDAAT/NE/methods.csv")
NE_organizations = read_csv("data/raw-data/WestDAAT/NE/organizations.csv")
NE_sites_missing = read_csv("data/raw-data/WestDAAT/NE/sites_missing.csv")
NE_sites = read_csv("data/raw-data/WestDAAT/NE/sites.csv")
NE_variables = read_csv("data/raw-data/WestDAAT/NE/variables.csv")
NE_allocations_missing = read_csv("data/raw-data/WestDAAT/NE/waterallocations_missing.csv")
NE_allocations = read_csv("data/raw-data/WestDAAT/NE/waterallocations.csv")
NE_sources_missing = read_csv("data/raw-data/WestDAAT/NE/watersources_missing.csv")
NE_sources = read_csv("data/raw-data/WestDAAT/NE/watersources.csv")

# New Mexico
NM_methods = read_csv("data/raw-data/WestDAAT/NM/methods.csv")
NM_organizations = read_csv("data/raw-data/WestDAAT/NM/organizations.csv")
NM_sites_missing = read_csv("data/raw-data/WestDAAT/NM/sites_missing.csv")
NM_sites = read_csv("data/raw-data/WestDAAT/NM/sites.csv")
NM_variables = read_csv("data/raw-data/WestDAAT/NM/variables.csv")
NM_allocations_missing = read_csv("data/raw-data/WestDAAT/NM/waterallocations_missing.csv")
NM_allocations = read_csv("data/raw-data/WestDAAT/NM/waterallocations.csv")
NM_sources_missing = read_csv("data/raw-data/WestDAAT/NM/watersources_missing.csv")
NM_sources = read_csv("data/raw-data/WestDAAT/NM/watersources.csv")

# Nevada
NV_methods = read_csv("data/raw-data/WestDAAT/NV/methods.csv")
NV_organizations = read_csv("data/raw-data/WestDAAT/NV/organizations.csv")
NV_sites_missing = read_csv("data/raw-data/WestDAAT/NV/sites_missing.csv")
NV_sites = read_csv("data/raw-data/WestDAAT/NV/sites.csv")
NV_variables = read_csv("data/raw-data/WestDAAT/NV/variables.csv")
NV_allocations_missing = read_csv("data/raw-data/WestDAAT/NV/waterallocations_missing.csv")
NV_allocations = read_csv("data/raw-data/WestDAAT/NV/waterallocations.csv")
NV_sources_missing = read_csv("data/raw-data/WestDAAT/NV/watersources_missing.csv")
NV_sources = read_csv("data/raw-data/WestDAAT/NV/watersources.csv")

# Oklahoma
OK_methods = read_csv("data/raw-data/WestDAAT/OK/methods.csv")
OK_organizations = read_csv("data/raw-data/WestDAAT/OK/organizations.csv")
OK_sites_missing = read_csv("data/raw-data/WestDAAT/OK/sites_missing.csv")
OK_sites = read_csv("data/raw-data/WestDAAT/OK/sites.csv")
OK_variables = read_csv("data/raw-data/WestDAAT/OK/variables.csv")
OK_allocations_missing = read_csv("data/raw-data/WestDAAT/OK/waterallocations_missing.csv")
OK_allocations = read_csv("data/raw-data/WestDAAT/OK/waterallocations.csv")
OK_sources_missing = read_csv("data/raw-data/WestDAAT/OK/watersources_missing.csv")
OK_sources = read_csv("data/raw-data/WestDAAT/OK/watersources.csv")

# Oregon
OR_methods = read_csv("data/raw-data/WestDAAT/OR/methods.csv")
OR_organizations = read_csv("data/raw-data/WestDAAT/OR/organizations.csv")
OR_sites_missing = read_csv("data/raw-data/WestDAAT/OR/sites_missing.csv")
OR_sites = read_csv("data/raw-data/WestDAAT/OR/sites.csv")
OR_variables = read_csv("data/raw-data/WestDAAT/OR/variables.csv")
OR_allocations_missing = read_csv("data/raw-data/WestDAAT/OR/waterallocations_missing.csv")
OR_allocations = read_csv("data/raw-data/WestDAAT/OR/waterallocations.csv")
OR_sources_missing = read_csv("data/raw-data/WestDAAT/OR/watersources_missing.csv")
OR_sources = read_csv("data/raw-data/WestDAAT/OR/watersources.csv")

# South Dakota
SD_methods = read_csv("data/raw-data/WestDAAT/SD/methods.csv")
SD_organizations = read_csv("data/raw-data/WestDAAT/SD/organizations.csv")
SD_sites_missing = read_csv("data/raw-data/WestDAAT/SD/sites_missing.csv")
SD_sites = read_csv("data/raw-data/WestDAAT/SD/sites.csv")
SD_variables = read_csv("data/raw-data/WestDAAT/SD/variables.csv")
SD_allocations_missing = read_csv("data/raw-data/WestDAAT/SD/waterallocations_missing.csv")
SD_allocations = read_csv("data/raw-data/WestDAAT/SD/waterallocations.csv")
SD_sources_missing = read_csv("data/raw-data/WestDAAT/SD/watersources_missing.csv")
SD_sources = read_csv("data/raw-data/WestDAAT/SD/watersources.csv")

# Texas TCEQ
TX_TCEQ_methods = read_csv("data/raw-data/WestDAAT/TX/TCEQ/methods.csv")
TX_TCEQ_organizations = read_csv("data/raw-data/WestDAAT/TX/TCEQ/organizations.csv")
TX_TCEQ_sites_missing = read_csv("data/raw-data/WestDAAT/TX/TCEQ/sites_missing.csv")
TX_TCEQ_sites = read_csv("data/raw-data/WestDAAT/TX/TCEQ/sites.csv")
TX_TCEQ_sites_amts_missing = read_csv("data/raw-data/WestDAAT/TX/TCEQ/sitespecificamounts_missing.csv")
TX_TCEQ_sites_amts = read_csv("data/raw-data/WestDAAT/TX/TCEQ/sitespecificamounts.csv")
TX_TCEQ_variables = read_csv("data/raw-data/WestDAAT/TX/TCEQ/variables.csv")
TX_TCEQ_allocations_missing = read_csv("data/raw-data/WestDAAT/TX/TCEQ/waterallocations_missing.csv")
TX_TCEQ_allocations = read_csv("data/raw-data/WestDAAT/TX/TCEQ/waterallocations.csv")
TX_TCEQ_sources_missing = read_csv("data/raw-data/WestDAAT/TX/TCEQ/watersources_missing.csv")
TX_TCEQ_sources = read_csv("data/raw-data/WestDAAT/TX/TCEQ/watersources.csv")

# Texas TWDB
TX_TWDB_methods = read_csv("data/raw-data/WestDAAT/TX/TWDB/methods.csv")
TX_TWDB_organizations = read_csv("data/raw-data/WestDAAT/TX/TWDB/organizations.csv")
TX_TWDB_sites_missing = read_csv("data/raw-data/WestDAAT/TX/TWDB/sites_missing.csv")
TX_TWDB_sites = read_csv("data/raw-data/WestDAAT/TX/TWDB/sites.csv")
TX_TWDB_variables = read_csv("data/raw-data/WestDAAT/TX/TWDB/variables.csv")
TX_TWDB_allocations_missing = read_csv("data/raw-data/WestDAAT/TX/TWDB/waterallocations_missing.csv")
TX_TWDB_allocations = read_csv("data/raw-data/WestDAAT/TX/TWDB/waterallocations.csv")
TX_TWDB_sources_missing = read_csv("data/raw-data/WestDAAT/TX/TWDB/watersources_missing.csv")
TX_TWDB_sources = read_csv("data/raw-data/WestDAAT/TX/TWDB/watersources.csv")

# Utah
UT_methods = read_csv("data/raw-data/WestDAAT/UT/methods.csv")
UT_organizations = read_csv("data/raw-data/WestDAAT/UT/organizations.csv")
UT_sites_missing = read_csv("data/raw-data/WestDAAT/UT/sites_missing.csv")
UT_sites = read_csv("data/raw-data/WestDAAT/UT/sites.csv")
UT_variables = read_csv("data/raw-data/WestDAAT/UT/variables.csv")
UT_allocations_missing = read_csv("data/raw-data/WestDAAT/UT/waterallocations_missing.csv")
UT_allocations = read_csv("data/raw-data/WestDAAT/UT/waterallocations.csv")
UT_sources_missing = read_csv("data/raw-data/WestDAAT/UT/watersources_missing.csv")
UT_sources = read_csv("data/raw-data/WestDAAT/UT/watersources.csv")

# Washington
WA_methods = read_csv("data/raw-data/WestDAAT/WA/methods.csv")
WA_organizations = read_csv("data/raw-data/WestDAAT/WA/organizations.csv")
WA_sites_missing = read_csv("data/raw-data/WestDAAT/WA/sites_missing.csv")
WA_sites = read_csv("data/raw-data/WestDAAT/WA/sites.csv")
WA_variables = read_csv("data/raw-data/WestDAAT/WA/variables.csv")
WA_allocations_missing = read_csv("data/raw-data/WestDAAT/WA/waterallocations_missing.csv")
WA_allocations = read_csv("data/raw-data/WestDAAT/WA/waterallocations.csv")
WA_sources_missing = read_csv("data/raw-data/WestDAAT/WA/watersources_missing.csv")
WA_sources = read_csv("data/raw-data/WestDAAT/WA/watersources.csv")

# Utah
UT_methods = read_csv("data/raw-data/WestDAAT/UT/methods.csv")
UT_organizations = read_csv("data/raw-data/WestDAAT/UT/organizations.csv")
UT_sites_missing = read_csv("data/raw-data/WestDAAT/UT/sites_missing.csv")
UT_sites = read_csv("data/raw-data/WestDAAT/UT/sites.csv")
UT_variables = read_csv("data/raw-data/WestDAAT/UT/variables.csv")
UT_allocations_missing = read_csv("data/raw-data/WestDAAT/UT/waterallocations_missing.csv")
UT_allocations = read_csv("data/raw-data/WestDAAT/UT/waterallocations.csv")
UT_sources_missing = read_csv("data/raw-data/WestDAAT/UT/watersources_missing.csv")
UT_sources = read_csv("data/raw-data/WestDAAT/UT/watersources.csv")

# Wyoming WaterAllocation
WY_1_methods = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/methods.csv")
WY_1_organizations = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/organizations.csv")
WY_1_sites_missing = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/sites_missing.csv")
WY_1_sites = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/sites.csv")
WY_1_variables = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/variables.csv")
WY_1_allocations_missing = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/waterallocations_missing.csv")
WY_1_allocations = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/waterallocations.csv")
WY_1_sources_missing = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/watersources_missing.csv")
WY_1_sources = read_csv("data/raw-data/WestDAAT/WY/WaterAllocations/watersources.csv")

# Wyoming WSGS
WY_WSGS_methods = read_csv("data/raw-data/WestDAAT/WY/WSGS/methods.csv")
WY_WSGS_organizations = read_csv("data/raw-data/WestDAAT/WY/WSGS/organizations.csv")
WY_WSGS_sites_missing = read_csv("data/raw-data/WestDAAT/WY/WSGS/sites_missing.csv")
WY_WSGS_sites = read_csv("data/raw-data/WestDAAT/WY/WSGS/sites.csv")
WY_WSGS_variables = read_csv("data/raw-data/WestDAAT/WY/WSGS/variables.csv")
WY_WSGS_allocations_missing = read_csv("data/raw-data/WestDAAT/WY/WSGS/waterallocations_missing.csv")
WY_WSGS_allocations = read_csv("data/raw-data/WestDAAT/WY/WSGS/waterallocations.csv")
WY_WSGS_sources_missing = read_csv("data/raw-data/WestDAAT/WY/WSGS/watersources_missing.csv")
WY_WSGS_sources = read_csv("data/raw-data/WestDAAT/WY/WSGS/watersources.csv")